server:
  port: ${PORT:8080}

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

  servlet:
    session:
      timeout: 60m

  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
    max-parameters: 2000


spring:
  application:
    name: Santosh Hospital

  main:
    banner-mode: console

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    # ❌ REMOVE username & password (important for Railway)
    
    hikari:
      pool-name: SantoshHikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2MB

  thymeleaf:
    cache: false

  web:
    resources:
      static-locations:
        - classpath:/static/

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# File Upload Path (Linux compatible)
file:
  upload-dir: /tmp/uploads/


# Razorpay
razorpay:
  key:
    id: ${RAZORPAY_KEY}
    secret: ${RAZORPAY_SECRET}


# Master User
master:
  user:
    name: ${MASTER_NAME:Santosh}
    email: ${MASTER_EMAIL:santoshtietech@gmail.com}


# Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | Santosh Hospital | %-5level | %logger - %msg%n"